### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (38,384) (37,384)

### ISSUE THREAD

**Issue by williambarberjr** [SeanLee97/AnglE#61]
Got this error while using this library to train an embedding model:
```
File "/usr/local/lib/python3.8/dist-packages/angle_emb/angle.py", line 986, in on_epoch_end
corrcoef, accuracy = self.evaluate_fn(self.valid_ds)
File "/usr/local/lib/python3.8/dist-packages/angle_emb/angle.py", line 1470, in evaluate
pred = (x_vecs[::2] * x_vecs[1::2]).sum(1)
ValueError: operands could not be broadcast together with shapes (38,384) (37,384)
```

I confirmed that `valid_ds` and `train_ds` were of even length, so ultimately I just modified one line of the evaluate method of the AnglE class. After this line:
`x_vecs = l2_normalize(x_vecs)`
I added:
```
if len(x_vecs) % 2 != 0:
    x_vecs = x_vecs[:-1]
```

Hopefully that doesn't break anything/everything else? Any thougths on what else might be the source of the issue?

Also, I attempted to restart training by running the same `angle.fit()` as I did when I started it but adjusting the `from_pretrained` to point to the most recent checkpoint:
`angle = AnglE.from_pretrained('/checkpoint-1100', max_length=512, pooling_strategy='cls').cuda()`

I don't see a `resume_from_checkpoint=True` argument option anywhere... so it's not clear that it's aware of how many epochs have already been run etc.

**Comment by SeanLee97** [comment]
hi @williambarberjr, to resume training, you can try to specify the checkpoint path to `pretrained_lora_path` if it is a  LoRA model or to `pretrained_model_path` if it is a standard model, as follows:

```python
from angle_emb import AnglE

angle = AnglE.from_pretrained(
    backbone='your_choice_backbone',
    pretrained_model_path='/checkpoint-1100',
    max_length=512,
    pooling_strategy='cls').cuda()
```

**Comment by williambarberjr** [comment]
I launched the training like this:

```
from datasets import load_dataset, DatasetDict
from angle_emb import AnglE, AngleDataTokenizer, DatasetFormats

# Load the dataset
ds = load_dataset("mydataset-here")

# Instantiate your AnglE model
angle = AnglE.from_pretrained('mixedbread-ai/mxbai-embed-large-v1', max_length=512, pooling_strategy='cls').cuda()

angle.set_prompt(prompt="Represent this sentence for searching relevant passages: ")

# Tokenize the data
train_ds = ds['train'].shuffle().map(AngleDataTokenizer(angle.tokenizer, angle.max_length), num_proc=8)
valid_ds = ds['validation'].map(AngleDataTokenizer(angle.tokenizer, angle.max_length), num_proc=8)
test_ds = ds['test'].map(AngleDataTokenizer(angle.tokenizer, angle.max_length), num_proc=8)

angle.fit(train_ds=train_ds,
    valid_ds=test_ds,
    output_dir='/',
    batch_size=13,
    epochs=5,
    learning_rate=2e-5,
    save_steps=30,
    eval_steps=1000,
    warmup_steps=0,
    gradient_accumulation_steps=315,
    loss_kwargs={
        'w1':0, 
        'w2':20,
        'w3':1,
        'cosine_tau':20,
        'ibn_tau':20,
        'angle_tau':20,
    },
    fp16=True,
    logging_steps=100)

```

So I'm just going to assume it's not a LoRA model, it's just a pretrained_model_path.

On a different note, when trying to test the model checkpoint like this:
```
from typing import Dict
import torch
import numpy as np
from transformers import AutoModel, AutoTokenizer
from sentence_transformers.util import cos_sim

# The model works really well with cls pooling (default) but also with mean poolin.
def pooling(outputs: torch.Tensor, inputs: Dict,  strategy: str = 'cls') -> np.ndarray:
    if strategy == 'cls':
        outputs = outputs[:, 0]
    elif strategy == 'mean':
        outputs = torch.sum(
            outputs * inputs["attention_mask"][:, :, None], dim=1) / torch.sum(inputs["attention_mask"])
    else:
        raise NotImplementedError
    return outputs.detach().cpu().numpy()

# 1. load model
model_id = '/path/to/folder/checkpoint-1100'
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id).cuda()

query = 'Represent this sentence for searching relevant passages: CCTV camera systems for warehouses'

docs = [
    query,
    "Vertical Lines Technologies FZE is a company that provides complete solutions in the sector of data collection and automatic identification. They offer a range of products, including barcode scanners, printers, PDAs, POS systems, and CCTV cameras, as well as services such as asset tracking, library management, retail inventory, school management, shipping and cargo, time and attendance, and warehouse management. Their target industries include automobile, facilities management, glass and aluminum, healthcare, jewelry, logistics and distribution, retail and chain stores, and warehouses. The company's values include quality, prompt delivery, integrity, customer focus, and respect and teamwork. They strive to provide the best quality products and services to their clients, with competitive prices and on-time delivery."
]


# 2. encode
inputs = tokenizer(docs, padding=True, return_tensors='pt')
for k, v in inputs.items():
    inputs[k] = v.cuda()

outputs = model(**inputs).last_hidden_state
embeddings = pooling(outputs, inputs, 'cls')

similarities = cos_sim(embeddings[0], embeddings[1:])
print('similarities:', similarities)
```

outputs is printing out as:
```
tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]]], device='cuda:0',
       grad_fn=<NativeLayerNormBackward0>)
```

Which naturally means that the similarities get printed as:
`similarities: tensor([[nan]])`

I tried a few different ways of replicating the code here: https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1

But couldn't seem to make the checkpoint work for me. I'm just attempting to validate that the model is getting better or at least staying the same "in domain" as a sanity check that I haven't messed anything else up.

**Comment by williambarberjr** [comment]
Very helpful. I was able to get it running on a single GPU, but the training will take quite a long time if I can't figure out how to distribute it across multiple GPUs. Here's my full script for attempting that:

```python
from datasets import load_dataset, DatasetDict, Dataset
from angle_emb import AnglE, AngleDataTokenizer, DatasetFormats
import os
import torch
import random
import json
from transformers import AutoTokenizer
from angle_emb import AnglE, AngleDataTokenizer

os.environ['WANDB_MODE'] = 'disabled'

data = []

with open('/root/train_small.jsonl', 'r') as file:
    for line in file:
        obj = json.loads(line)
        obj['text'] = f'Represent this sentence for searching relevant passages: {obj["text"]}'
        data.append(obj)

random.shuffle(data)
train_ds = Dataset.from_list(data)

test_data = []

with open('/root/test.jsonl', 'r') as file:
    for line in file:
        obj = json.loads(line)
        obj['text'] = f'Represent this sentence for searching relevant passages: {obj["text"]}'
        test_data.append(obj)

random.shuffle(test_data)
test_ds = Dataset.from_list(test_data)

validation_data = []

with open('/root/validation.jsonl', 'r') as file:
    for line in file:
        obj = json.loads(line)
        obj['text'] = f'Represent this sentence for searching relevant passages: {obj["text"]}'
        validation_data.append(obj)

random.shuffle(validation_data)
valid_ds = Dataset.from_list(validation_data)

max_len = 512
model_id = 'mixedbread-ai/mxbai-embed-large-v1'

tokenizer = AutoTokenizer.from_pretrained(model_id)
train_ds = train_ds.shuffle().map(AngleDataTokenizer(tokenizer, max_len), num_proc=8)
valid_ds = valid_ds.map(AngleDataTokenizer(tokenizer, max_len), num_proc=8)
test_ds = test_ds.map(AngleDataTokenizer(tokenizer, max_len), num_proc=8)

angle = AnglE.from_pretrained(model_id, max_length=max_len, torch_dtype=torch.float32, pooling_strategy='cls').cuda()

if torch.cuda.device_count() > 1:
    angle.backbone = torch.nn.DataParallel(angle.backbone)

angle.fit(train_ds=train_ds,
    valid_ds=valid_ds,
    output_dir='/root',
    batch_size=10 * torch.cuda.device_count(),  # Increase batch size based on the number of GPUs
    epochs=5,
    learning_rate=1e-5,
    save_steps=100,
    eval_steps=1000,
    warmup_steps=0,
    gradient_accumulation_steps=400 // torch.cuda.device_count(),  # Adjust gradient accumulation steps
    loss_kwargs={
        'w1':0, 
        'w2':20,
        'w3':1,
        'cosine_tau':20,
        'ibn_tau':20,
        'angle_tau':20,
    },
    fp16=True,
    logging_steps=10)
```

I'm getting this error:
```
/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(>dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
Traceback (most recent call last):
  File "/root/runMultiGPUTraining.py", line 63, in <module>
    angle.fit(train_ds=train_ds,
  File "/usr/local/lib/python3.8/dist-packages/angle_emb/angle.py", line 1449, in fit
    trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1928, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.8/dist-packages/accelerate/data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
     current_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.8/dist-packages/angle_emb/angle.py", line 603, in __call__
    input_ids = feature['input_ids']
KeyError: 'input_ids'
^M  0%|          | 0/30 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/runMultiGPUTraining.py", line 63, in <module>
    angle.fit(train_ds=train_ds,
  File "/usr/local/lib/python3.8/dist-packages/angle_emb/angle.py", line 1449, in fit
    trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1928, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.8/dist-packages/accelerate/data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.8/dist-packages/angle_emb/angle.py", line 603, in __call__
    input_ids = feature['input_ids']
KeyError: 'input_ids'
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.1) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[2024-03-14 01:13:14,026] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 6198 closing signal SIGTERM
[2024-03-14 01:13:14,291] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 6199) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/root/runMultiGPUTraining.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-14_01:13:14
  host      : eed91803ec3b
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 6199)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

I've confirmed that the datasets appear to be formatted correctly given that when I print them they look like this:
```
train_ds: Dataset({
    features: ['text', 'positive', 'negative', 'input_ids', 'token_type_ids', 'attention_mask', 'labels', 'seperate_ids', 'extra'],
    num_rows: 40000
})
valid_ds: Dataset({
    features: ['text', 'positive', 'negative', 'input_ids', 'token_type_ids', 'attention_mask', 'labels', 'seperate_ids', 'extra'],
    num_rows: 40000
})
test_ds: Dataset({
    features: ['text', 'positive', 'negative', 'input_ids', 'token_type_ids', 'attention_mask', 'labels', 'seperate_ids', 'extra'],
    num_rows: 40000
})
```

Best I can tell, the do have an "input_ids" key. So I can't seem to determine the source of that error.

I'm calling the code with this command on a 2 x RTX 4090 setup (just to test the distributed code):
NCCL_P2P_DISABLE=1 NCCL_IB_DISABLE=1 torchrun --nproc_per_node=2 /root/runMultiGPUTraining.py 2>&1 | tee /root/output.txt

Any thoughts on what's causing this issue? I was getting a similar issue on one GPU, couldn't figure out what the issue was but mimicing exactly how your example code imported and setup the data resolved the issue, however, for some reason that doesn't seem to resolve the issue in a distributed setting?

**Comment by SeanLee97** [comment]
hi @williambarberjr , i checked it in multi-GPU setting and did not reproduce your problem. It works fine in my training. 

I fixed the NaN issue several minutes ago. Could you update the angle_emb to v0.3.9 and try to train the model using the [train_cli.py](https://github.com/SeanLee97/AnglE/blob/main/angle_emb/train_cli.py)

Here is an example to train with `train_cli.py`:

1) prepare the data into a jsonl file, as follows:

```bash
$ head -3 snli_5k.jsonl

{"text": "A person on a horse jumps over a broken down airplane.", "positive": "A person is outdoors, on a horse.", "negative": "A person is at a diner, ordering an omelette."}
{"text": "Children smiling and waving at camera", "positive": "There are children present", "negative": "The kids are frowning"}
{"text": "A boy is jumping on skateboard in the middle of a red bridge.", "positive": "The boy does a skateboarding trick.", "negative": "The boy skates down the sidewalk."}
```

2) train the model using following script:

```bash
NCCL_P2P_DISABLE=1 NCCL_IB_DISABLE=1 CUDA_VISIBLE_DEVICES=0,1 WANDB_MODE=disabled CUDA_VISIBLE_DEVICES=2,3 torchrun --nproc_per_node=2 --master_port=2345 train_cli.py \
--model_name_or_path mixedbread-ai/mxbai-embed-large-v1 \
--train_name_or_path ./snli_5k.jsonl --save_dir mxbai-snli-ckpts \
--w1 0. --w2 20.0 --w3 1.0 --angle_tau 20.0 --learning_rate 3e-6 --maxlen 64 \
--pooling_strategy cls \
--epochs 1 \
--batch_size 32 \
--logging_steps 100 \
--warmup_steps 200 \
--save_steps 1000 --seed 42 --gradient_accumulation_steps 2 --fp16 1 --torch_dtype 'float32'
```

When the training is done, the model will be saved to `mxbai-snli-ckpts`, you can load it as follows:

```python
from angle_emb import AnglE

angle = AnglE.from_pretrained('mixedbread-ai/mxbai-embed-large-v1', pretrained_model_path='mxbai-snli-ckpts').cuda()

...
```

**Comment by williambarberjr** [comment]
Thanks for your help. The training is running smoothly now distributed across several GPUs. I've got one running with an effective batch size of 30k+ and another with an effective batch size of about 4k.

![image](https://github.com/SeanLee97/AnglE/assets/9202147/4291db64-f307-41d6-9f56-8b5fc42de1e5)

![image](https://github.com/SeanLee97/AnglE/assets/9202147/8012cded-ff47-461c-ab41-e860a38ccf1b)

The grad_norm values for the 4k batch size seem to be a bit all over the place - does that suggest an issue to you?
